version: '3.7'
services:
  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    ports:
      - '6831:6831/udp'
      - '16686:16686'
      - '5778:5778'
      - '5775:5775/udp'
      - '6832:6832/udp'
      - '14268:14268'
      - '14250:14250'
    networks:
      - jaeger-example
      
      
  iris5_digitalbanking:
    image: dotnet6_db2
    container_name: dotnet6_digitalbanking
    volumes:
    - /home/sana/:/home/digitalbanking/
    working_dir: /dockerappNet6 
    networks:
      - jaeger-example        
    depends_on:
      - jaeger    
    ports:
      - '8080:5000'
    environment:
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      
      
networks:
  jaeger-example:

#On prem CICD